package y2ssh.zhangcuishan.entity;

import java.util.Date;


/**
 * Bid generated by MyEclipse - Hibernate Tools
 */

public class Bid  implements java.io.Serializable {


    // Fields    

	private static final long serialVersionUID = -7098966278403802603L;
	private Long bidId;
//     private Long goodsId;
//     private Long buyerId;
     private Date bidTime;
     private Double bidPrice;
     private Integer bidStatus;
     
     private Goods goods;
     private User buyer;


    // Constructors

    public User getBuyer() {
		return buyer;
	}


	public void setBuyer(User buyer) {
		this.buyer = buyer;
	}


	public Goods getGoods() {
		return goods;
	}


	public void setGoods(Goods goods) {
		this.goods = goods;
	}


	/** default constructor */
    public Bid() {
    }

    
    /** full constructor */
    public Bid(Goods goodsId, User buyerId, Date bidTime, Double bidPrice, Integer bidStatus) {
        this.goods = goodsId;
        this.buyer = buyerId;
        this.bidTime = bidTime;
        this.bidPrice = bidPrice;
        this.bidStatus = bidStatus;
    }

   
    // Property accessors

    public Long getBidId() {
        return this.bidId;
    }
    
    public void setBidId(Long bidId) {
        this.bidId = bidId;
    }

//    public Long getGoodsId() {
//        return this.goodsId;
//    }
//    
//    public void setGoodsId(Long goodsId) {
//        this.goodsId = goodsId;
//    }
//
//    public Long getBuyerId() {
//        return this.buyerId;
//    }
//    
//    public void setBuyerId(Long buyerId) {
//        this.buyerId = buyerId;
//    }

    public Date getBidTime() {
        return this.bidTime;
    }
    
    public void setBidTime(Date bidTime) {
        this.bidTime = bidTime;
    }

    public Double getBidPrice() {
        return this.bidPrice;
    }
    
    public void setBidPrice(Double bidPrice) {
        this.bidPrice = bidPrice;
    }

    public Integer getBidStatus() {
        return this.bidStatus;
    }
    
    public void setBidStatus(Integer bidStatus) {
        this.bidStatus = bidStatus;
    }
   

}