package y2ssh.zhangcuishan.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import y2ssh.zhangcuishan.util.JbUtils;


/**
 * Goods generated by MyEclipse - Hibernate Tools
 */

public class Goods  implements java.io.Serializable {


    // Fields    

	private static final long serialVersionUID = -4649216120593895204L;
	 private Long goodsId;
     private String goodsName;
     private Double goodsPrice;
     private String goodsPic;
     private String goodsDesc;
     private Date beginTime;
     private Date endTime;
     
     public String toString(){
    	 return this.goodsId + "." + this.goodsName;
     }
     private Set bids = new HashSet(0);
//     private Long salerId;
//     private Long buyerId;
     private User saler;
     private User buyer;
     
     private Integer goodsStatus;


    // Constructors

    /** default constructor */
    public Goods() {
    }

	/** minimal constructor */
    public Goods(String goodsName, Double goodsPrice, User salerId, Integer goodsStatus) {
        this.goodsName = goodsName;
        this.goodsPrice = goodsPrice;
        this.saler = salerId;
        this.goodsStatus = goodsStatus;
    }
    
    /** full constructor */
    public Goods(String goodsName, Double goodsPrice, String goodsPic, String goodsDesc, User salerId, Date beginTime, Date endTime, User buyerId, Integer goodsStatus) {
        this.goodsName = goodsName;
        this.goodsPrice = goodsPrice;
        this.goodsPic = goodsPic;
        this.goodsDesc = goodsDesc;
        this.saler = salerId;
        this.beginTime = beginTime;
        this.endTime = endTime;
        this.buyer = buyerId;
        this.goodsStatus = goodsStatus;
    }

   
    // Property accessors

    public Long getGoodsId() {
        return this.goodsId;
    }
    
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    public String getGoodsName() {
        return this.goodsName;
    }
    
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    public Double getGoodsPrice() {
        return this.goodsPrice;
    }
    
    public void setGoodsPrice(Double goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    public String getGoodsPic() {
        return this.goodsPic;
    }
    
    public void setGoodsPic(String goodsPic) {
        this.goodsPic = goodsPic;
    }

    public String getGoodsDesc() {
        return this.goodsDesc;
    }
    
    public void setGoodsDesc(String goodsDesc) {
        this.goodsDesc = goodsDesc;
    }

//    public Long getSalerId() {
//        return this.saler;
//    }
//    
//    public void setSalerId(Long salerId) {
//        this.salerId = salerId;
//    }

    public Date getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

//    public Long getBuyerId() {
//        return this.buyerId;
//    }
//    
//    public void setBuyerId(Long buyerId) {
//        this.buyerId = buyerId;
//    }

    public User getBuyer() {
		return buyer;
	}

	public void setBuyer(User buyer) {
		this.buyer = buyer;
	}

	public User getSaler() {
		return saler;
	}

	public void setSaler(User saler) {
		this.saler = saler;
	}

	public Integer getGoodsStatus() {
        return this.goodsStatus;
    }
    
    public void setGoodsStatus(Integer goodsStatus) {
        this.goodsStatus = goodsStatus;
    }

	public Set getBids() {
		return bids;
	}

	public void setBids(Set bids) {
		this.bids = bids;
	}
   



	public String getBeginTimeString() {
		return JbUtils.formatDate(this.beginTime);
	}

	public void setBeginTimeString(String beginTime) {
		this.beginTime = JbUtils.parseDate(beginTime);
	}

	public String getEndTimeString() {
		return JbUtils.formatDate(this.endTime);
	}

	public void setEndTimeString(String endTime) {
		this.endTime = JbUtils.parseDate(endTime);
	}

}